/*********************************************************************************************************************
This file demonsstrates the usage of HashSet in C#.
It includes examples of creating a HashSet, adding elements, checking for existence,
removing elements, and iterating through the HashSet.

A hashset is a collection that contains no duplicate elements and has no particular order. 
It stores elements based on the index generated by hash codes of the elements modulo the size of the underlying hashset
It is optimized for fast lookups, additions, and deletions. 

Syntax -  HashSet<T> hashSet = new HashSet<T>();
    where T is the type of elements in the HashSet.

Namespace -  System.Collections.Generic

Example Usage -
    HashSet<int> numbers = new HashSet<int>();
    numbers.Add(1);
    numbers.Add(2);
*********************************************************************************************************************/

using System;
using System.Collections.Generic;

namespace Dictionary_HashSet
{
    public class Program
    {
        static void Main()
        {
            // create a hashset of strings
            HashSet<string> fruits = new HashSet<string>();

            // add elements to the hashset
            fruits.Add("Apple");
            fruits.Add("Banana");
            fruits.Add("Orange");
            fruits.Add("Mango");
            fruits.Add("Grapes");
            fruits.Add("Pineapple");
            fruits.Add("Kiwi");
            fruits.Add("Peach");
            fruits.Add("Watermelon");
            fruits.Add("Strawberry");


            // get the count of elements in the hashset - fruits.Count
            Console.WriteLine("\nCount of fruits in the hashset: " + fruits.Count);

            //Iterate through the hashset
            Console.WriteLine("\nFruits in the hashset:");
            foreach (var fruit in fruits)
            {
                Console.WriteLine(fruit);
            }

            // check if an element exists in the hashset
            bool hasMango = fruits.Contains("Mango");
            Console.WriteLine("\nDoes the hashset contain Mango? " + hasMango);

            // remove an element from the hashset
            fruits.Remove("Banana");
            Console.WriteLine("\nAfter removing Banana, count of fruits in the hashset: " + fruits.Count);

            //RemoveWhere example - remove all fruits that start with the letter 'P'
            fruits.RemoveWhere(fruit => fruit.StartsWith("P"));
            Console.WriteLine("\nAfter removing fruits that start with 'P', count of fruits in the hashset: " + fruits.Count);

            //UnionWith example - add more fruits to the hashset
            HashSet<string> moreFruits = new HashSet<string> { "Papaya", "Guava", "Cherry" };
            fruits.UnionWith(moreFruits);
            Console.WriteLine("\nAfter adding more fruits, count of fruits in the hashset: " + fruits.Count);

            //IntersectWith example - keep only fruits that are also in another hashset
            HashSet<string> tropicalFruits = new HashSet<string> { "Mango", "Pineapple", "Papaya", "Banana" };
            fruits.IntersectWith(tropicalFruits);
            Console.WriteLine("\nAfter intersecting with tropical fruits, count of fruits in the hashset: " + fruits.Count);

            //Clear the hashset
            fruits.Clear();
            Console.WriteLine("\nAfter clearing, count of fruits in the hashset: " + fruits.Count);
        }
    }
}
